/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author gusic
 */
public class Cadastro_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_Clientes
     */
    public Cadastro_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botao_Sair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Cadastro_Clientes = new javax.swing.JMenuItem();
        Menu_Cadastro_Fornecedores = new javax.swing.JMenuItem();
        Menu_Cadastro_Produtos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        Botao_Sair.setText("Sair");

        jMenu1.setText("Cadastros");

        Menu_Cadastro_Clientes.setText("Clientes");
        jMenu1.add(Menu_Cadastro_Clientes);

        Menu_Cadastro_Fornecedores.setText("Fornecedores");
        Menu_Cadastro_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Cadastro_FornecedoresActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Cadastro_Fornecedores);

        Menu_Cadastro_Produtos.setText("Produtos");
        jMenu1.add(Menu_Cadastro_Produtos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produtos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 698, Short.MAX_VALUE)
                .addComponent(Botao_Sair))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 297, Short.MAX_VALUE)
                .addComponent(Botao_Sair))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Cadastro_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Cadastro_FornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Cadastro_FornecedoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Sair;
    private javax.swing.JMenuItem Menu_Cadastro_Clientes;
    private javax.swing.JMenuItem Menu_Cadastro_Fornecedores;
    private javax.swing.JMenuItem Menu_Cadastro_Produtos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
