/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Produtos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fofao
 */
public class CadastroProdutos2 extends javax.swing.JInternalFrame {
    public void Consultar() throws SQLException {
        DefaultTableModel grid0 = (DefaultTableModel) Tabela_Produtos.getModel();
        grid0.setNumRows(0);
        Connection conn = null;
        Conec.Conexao bd = new Conec.Conexao();
        conn = bd.getConnection();
        Statement stm = null;
        ResultSet rs = null;
        String SQLConsulta = "SELECT * FROM Produtos";
        stm = conn.createStatement();
        rs = stm.executeQuery(SQLConsulta);
        while (rs.next()) {
            String recebe_id = rs.getString("Codigo");
            String recebe_nome = rs.getString("Nome");
            String recebe_precocompra = rs.getString("PrecoCompra");
            String recebe_precovenda = rs.getString("PrecoVenda");
            String recebe_quantidade = rs.getString("Quantidade");

            DefaultTableModel grid = (DefaultTableModel) Tabela_Produtos.getModel();
            grid0.addRow(new String[]{recebe_id, recebe_nome, recebe_precocompra, recebe_precovenda, recebe_quantidade});
        }
        rs.close();
        stm.close();
    }
    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Venda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Botao_Alterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Botao_Excluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Text_id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Botao_Sair = new javax.swing.JButton();
        Botao_Cadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Produtos = new javax.swing.JTable();
        Text_Quant = new javax.swing.JTextField();
        Text_Compra = new javax.swing.JTextField();
        Text_Nome = new javax.swing.JTextField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Nome do Produto:");

        Botao_Alterar.setText("Alterar");
        Botao_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_AlterarActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço de Venda:");

        Botao_Excluir.setText("Excluir");
        Botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_ExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço de Compra:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Código:");

        Botao_Sair.setText("Sair");
        Botao_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_SairMouseClicked(evt);
            }
        });
        Botao_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_SairActionPerformed(evt);
            }
        });

        Botao_Cadastro.setText("Cadastrar");
        Botao_Cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botao_CadastroMouseClicked(evt);
            }
        });
        Botao_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_CadastroActionPerformed(evt);
            }
        });

        Tabela_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço de Compra", "Preço de Venda", "Quantidade"
            }
        ));
        Tabela_Produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_ProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Produtos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_Cadastro)
                        .addGap(18, 18, 18)
                        .addComponent(Botao_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(Botao_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_Sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Text_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Text_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Text_Quant))
                            .addComponent(jLabel4))
                        .addGap(0, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Text_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_Cadastro)
                    .addComponent(Botao_Sair)
                    .addComponent(Botao_Alterar)
                    .addComponent(Botao_Excluir))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_AlterarActionPerformed
        if ("".equals(Text_Nome.getText()) || "".equals(Text_Compra.getText()) || "".equals(Text_Venda.getText()) || "".equals(Text_Quant.getText())) {
            JOptionPane.showMessageDialog(null, "Insira valores válido", "Problema", JOptionPane.ERROR_MESSAGE);
        } else {
        try {
            int resp;
            resp = JOptionPane.showConfirmDialog(null, "Deseja atualizar os dados do produto?");
        
        if (resp == JOptionPane.YES_OPTION){
            Connection conn = new Conec.Conexao().getConnection();
            Produtos p = new Produtos();

                p.setId(Integer.parseInt(Text_id.getText()));
                p.setNome(Text_Nome.getText());
                p.setPrecocompra(Double.parseDouble(Text_Compra.getText()));
                p.setPrecovenda(Double.parseDouble(Text_Venda.getText()));
                p.setQuantidade(Integer.parseInt(Text_Quant.getText()));

            p.Alterar(conn);
            Consultar();
            Text_id.setText("");
            Text_Nome.setText("");
            Text_Compra.setText("");
            Text_Venda.setText("");
            Text_Quant.setText("");
            
            JOptionPane.showMessageDialog(null, "Os dados do produto foram atualizados.");
            
        }else{
            JOptionPane.showMessageDialog(null, "Nenhuma informação foi alterada.");
        }
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Problema", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos2.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_Botao_AlterarActionPerformed

    private void Botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_ExcluirActionPerformed
        try {
            int resp;
            resp = JOptionPane.showConfirmDialog(null, "Deseja EXCLUIR este produto?");
        
        if (resp == JOptionPane.YES_OPTION){
            Connection conn = new Conec.Conexao().getConnection();
            Produtos p = new Produtos();
            p.setId(Integer.parseInt(Text_id.getText()));

            p.Deletar(conn);

            Consultar();
            Text_id.setText("");
            Text_Nome.setText("");
            Text_Compra.setText("");
            Text_Venda.setText("");
            Text_Quant.setText("");
            
            JOptionPane.showMessageDialog(null, "O produto foi excluído.");
            
        }else{
            JOptionPane.showMessageDialog(null, "Nenhuma informação foi alterada.");
        }
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Problema", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Botao_ExcluirActionPerformed

    private void Botao_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_SairMouseClicked
        dispose();
    }//GEN-LAST:event_Botao_SairMouseClicked

    private void Botao_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_SairActionPerformed

    private void Botao_CadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botao_CadastroMouseClicked
        if ("".equals(Text_id.getText())){
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "Deseja concluir este cadastro?");
        
        if (resp == JOptionPane.YES_OPTION){
        if ("".equals(Text_Nome.getText()) || "".equals(Text_Compra.getText()) || "".equals(Text_Venda.getText()) || "".equals(Text_Quant.getText())) {
            JOptionPane.showMessageDialog(null, "Insira valores válido", "Problema", JOptionPane.ERROR_MESSAGE);
        } else {    
        }
        try {
            Connection conn = new Conec.Conexao().getConnection();
            Produtos p = new Produtos();
            
            p.setNome(Text_Nome.getText());
            p.setPrecocompra(Double.parseDouble(Text_Compra.getText()));
            p.setPrecovenda(Double.parseDouble(Text_Venda.getText()));
            p.setQuantidade(Integer.parseInt(Text_Quant.getText()));
            
            p.cadastrar(conn);

            Consultar();
            Text_id.setText("");
            Text_Nome.setText("");
            Text_Compra.setText("");
            Text_Venda.setText("");
            Text_Quant.setText("");
            
            JOptionPane.showMessageDialog(null, "Produto cadastrado.");
            
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela", "Problema", JOptionPane.ERROR_MESSAGE);
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Insira valores válidos", "Problema", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos2.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Cadastro Cancelado.");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Valor Já cadastrado", "Problema", JOptionPane.ERROR_MESSAGE);
            
            Connection conn = new Conec.Conexao().getConnection();
            Produtos p = new Produtos();
            p.Alterar(conn);
            try {
                Consultar();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroProdutos2.class.getName()).log(Level.SEVERE, null, ex);
            }
            Text_id.setText("");
            Text_Nome.setText("");
            Text_Compra.setText("");
            Text_Venda.setText("");
            Text_Quant.setText("");
        }
    }//GEN-LAST:event_Botao_CadastroMouseClicked

    private void Botao_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_CadastroActionPerformed

    private void Tabela_ProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_ProdutosMouseClicked
        DefaultTableModel grid0 = (DefaultTableModel) Tabela_Produtos.getModel();

        Text_id.setText((String) Tabela_Produtos.getValueAt(Tabela_Produtos.getSelectedRow(), 0));
        Text_Nome.setText((String) Tabela_Produtos.getValueAt(Tabela_Produtos.getSelectedRow(), 1));
        Text_Venda.setText((String) Tabela_Produtos.getValueAt(Tabela_Produtos.getSelectedRow(), 3));
        Text_Compra.setText((String) Tabela_Produtos.getValueAt(Tabela_Produtos.getSelectedRow(), 2));
        Text_Quant.setText((String) Tabela_Produtos.getValueAt(Tabela_Produtos.getSelectedRow(), 4));
    }//GEN-LAST:event_Tabela_ProdutosMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        try {
            Consultar();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Alterar;
    private javax.swing.JButton Botao_Cadastro;
    private javax.swing.JButton Botao_Excluir;
    private javax.swing.JButton Botao_Sair;
    private javax.swing.JTable Tabela_Produtos;
    private javax.swing.JTextField Text_Compra;
    private javax.swing.JTextField Text_Nome;
    private javax.swing.JTextField Text_Quant;
    private javax.swing.JTextField Text_Venda;
    private javax.swing.JLabel Text_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
